using Microsoft.EntityFrameworkCore;
using Budgett.Models;

namespace Budgett.Data
{
    public class BudgettContext : DbContext
    {
        public BudgettContext(DbContextOptions<BudgettContext> options)
            : base(options)
        { }

        public DbSet<Account> Account { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Goal> Goal { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<Transaction> Transaction { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // If a model has a date field that should be generated by the database
        }
    }
}